CREATE DATABASE DB_IRRIGA_VIDA;

USE DB_IRRIGA_VIDA;

-- CRIAÇÃO DA TABELA PARA CONTROLE DE USUÁRIO
CREATE TABLE TB_USUARIO (
	ID_USUARIO INTEGER PRIMARY KEY NOT NULL IDENTITY (1,1),
	NOME_USUARIO VARCHAR(30) NOT NULL,
	SENHA_USU VARCHAR(10) NOT NULL,
	--SENHA_USU VARCHAR(MAX) NOT NULL,
	-- SENHA_USU VARBINARY(MAX) NOT NULL,
	DT_CADASTRO_USU DATETIME NOT NULL,
	EMAIL_USU VARCHAR (50),
	DT_ALTERACAO_USU DATETIME,
	STATUS_USUARIO CHAR (1) NOT NULL CHECK (STATUS_USUARIO IN ('A','I')), -- A - Ativado | I - Desativado
	PERFIL_USUARIO CHAR (1) NOT NULL  CHECK (PERFIL_USUARIO IN ('A','U')) DEFAULT 'U' -- A - Administrador | U - Usuário
);

-- ADICIONANDO VALORES 
INSERT INTO TB_USUARIO(NOME_USUARIO, SENHA_USU,DT_CADASTRO_USU,EMAIL_USU,STATUS_USUARIO,PERFIL_USUARIO)
VALUES('ALICE','ADM12345','02/10/2021','alice.alves@fatec.sp.gov.br','A','U');

INSERT INTO TB_USUARIO(NOME_USUARIO, SENHA_USU,DT_CADASTRO_USU,EMAIL_USU,STATUS_USUARIO,PERFIL_USUARIO)
VALUES('LUCAS','ADM12345','02/10/2021','lucas.romera@fatec.sp.gov.br','I','U');

INSERT INTO TB_USUARIO(NOME_USUARIO, SENHA_USU,DT_CADASTRO_USU,EMAIL_USU,STATUS_USUARIO,PERFIL_USUARIO)
VALUES('FABRICIA','ADM12345','02/10/2021','fabricia.gomes@fatec.sp.gov.br','A','A');

INSERT INTO TB_USUARIO(NOME_USUARIO, SENHA_USU,DT_CADASTRO_USU,EMAIL_USU,STATUS_USUARIO,PERFIL_USUARIO)
VALUES('MATEUS MARQUES','ADM12345','02/10/2021','mateus.marques@fatec.sp.gov.br','I','A');

INSERT INTO TB_USUARIO(NOME_USUARIO, SENHA_USU,DT_CADASTRO_USU,EMAIL_USU,STATUS_USUARIO,PERFIL_USUARIO)
VALUES('LUCAS ROMERA','ADM12345','02/10/2021','lucas.romera@fatec.sp.gov.br','A','U');


-- TABELA DE CONTROLE DE EQUIPAMENTO
CREATE TABLE TB_EQUIPAMENTO(
	ID_EQUIPAMENTO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	DESCRICAO VARCHAR(50) NOT NULL,
	VALOR_EQUIPAMENTO VARCHAR(10) NOT NULL,
	--VALOR_EQUIPAMENTO DECIMAL(10,5) NOT NULL,
	DT_ULTIMA_MAN DATETIME -- DATA DA ULTIMA MANUTENÇÃO
);


INSERT INTO TB_EQUIPAMENTO(DESCRICAO, VALOR_EQUIPAMENTO, DT_ULTIMA_MAN)
VALUES('Irrigador Giratório', 123,'02/10/2020');

INSERT INTO TB_EQUIPAMENTO(DESCRICAO, VALOR_EQUIPAMENTO,DT_ULTIMA_MAN)
VALUES('Auto Temporizador',5000,'02/10/2019');

INSERT INTO TB_EQUIPAMENTO(DESCRICAO, VALOR_EQUIPAMENTO,DT_ULTIMA_MAN)
VALUES('Auto Temporizador Automatic',200,'02/10/2019');

INSERT INTO TB_EQUIPAMENTO(DESCRICAO, VALOR_EQUIPAMENTO,DT_ULTIMA_MAN)
VALUES('Irrigador hortaliças simples',10000,'02/10/2019');

INSERT INTO TB_EQUIPAMENTO(DESCRICAO, VALOR_EQUIPAMENTO,DT_ULTIMA_MAN)
VALUES('Mangueira para irrigação simples',50,'02/10/2019');


-- TABELA DE AGENDAMENTOS DE MANUTENÇÃO
CREATE TABLE TB_AGENDAMENTOS (
	ID_AGENDAMENTO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	ID_USUARIO INTEGER NOT NULL,
	ID_EQUIPAMENTO INTEGER NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL,  
	TIPO_AGEN CHAR(1) NOT NULL  CHECK (TIPO_AGEN IN ('P','U')), -- P -PREVENTIVA | U - URGENCIA
	DT_MARCADA_AGEND DATETIME NOT NULL,
	STATUS_AGEN CHAR(1) NOT NULL  CHECK (STATUS_AGEN  IN ('E','P','C')),  -- E - EFETUADO | P - PENDENTE | C- CANCELADO
	FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
	FOREIGN KEY(ID_EQUIPAMENTO) REFERENCES TB_EQUIPAMENTO (ID_EQUIPAMENTO)
);
INSERT INTO TB_AGENDAMENTOS(ID_USUARIO, ID_EQUIPAMENTO,DESCRICAO, TIPO_AGEN, DT_MARCADA_AGEND, STATUS_AGEN)
VALUES(1,1,'Preventiva','P','10/10/2021','P');

INSERT INTO TB_AGENDAMENTOS(ID_USUARIO, ID_EQUIPAMENTO,DESCRICAO, TIPO_AGEN, DT_MARCADA_AGEND, STATUS_AGEN)
VALUES(1,2,'Problema de vazamento','U','18/10/2021','C');

INSERT INTO TB_AGENDAMENTOS(ID_USUARIO, ID_EQUIPAMENTO,DESCRICAO, TIPO_AGEN, DT_MARCADA_AGEND, STATUS_AGEN)
VALUES(3,4,'Problema de fabricação','U','01/01/2021','P');

INSERT INTO TB_AGENDAMENTOS(ID_USUARIO, ID_EQUIPAMENTO,DESCRICAO, TIPO_AGEN, DT_MARCADA_AGEND, STATUS_AGEN)
VALUES(2,2,'Preventiva no prazo','P','01/01/2020','C');

INSERT INTO TB_AGENDAMENTOS(ID_USUARIO, ID_EQUIPAMENTO,DESCRICAO, TIPO_AGEN, DT_MARCADA_AGEND, STATUS_AGEN)
VALUES(4,3,'Limpeza','U','18/05/2021','C');


CREATE TABLE TB_PLANTA (
	ID_PLANTA INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME_POPULAR VARCHAR(30) NOT NULL,
	DT_CADASTRO DATETIME,
	OBSERVACOES VARCHAR(120),
	TIPO_PLANTA VARCHAR(10),
	ORIGEM VARCHAR(20),
	NOME_CIENT VARCHAR(50),
	FAMILIA VARCHAR(30),
	CLIMA VARCHAR(20)
);
INSERT INTO TB_PLANTA(NOME_POPULAR, DT_CADASTRO,OBSERVACOES, TIPO_PLANTA, ORIGEM, NOME_CIENT,FAMILIA,CLIMA)
VALUES('Alface Verde',SYSDATETIME(),'Manter de 20 a 25ºC','Hortence','Mediterraneo','Lactuca sativa','Hortalicas','temp amenas');

INSERT INTO TB_PLANTA(NOME_POPULAR, DT_CADASTRO, TIPO_PLANTA, ORIGEM, NOME_CIENT,FAMILIA,CLIMA)
VALUES('Tomate',SYSDATETIME(),'Fruta','Mexico','Solanum lycopersicum','Fruta','quente');

INSERT INTO TB_PLANTA(NOME_POPULAR, DT_CADASTRO, TIPO_PLANTA, FAMILIA,CLIMA)
VALUES('Morango',SYSDATETIME(),'Fruta','Fruta','frio');

INSERT INTO TB_PLANTA(NOME_POPULAR, DT_CADASTRO, TIPO_PLANTA, ORIGEM, NOME_CIENT,FAMILIA,CLIMA)
VALUES('Acelora',SYSDATETIME(),'Fruta','Brasil','Malpighia emarginata','Fruta','quente');

INSERT INTO TB_PLANTA(NOME_POPULAR, DT_CADASTRO, TIPO_PLANTA, ORIGEM, NOME_CIENT,FAMILIA,CLIMA)
VALUES('Uva',SYSDATETIME(),'Fruta','Europa','Grapevines (Videiras)','Fruta','frio');

CREATE TABLE TB_FERTILIZANTE (
	ID_FERTILIZANTE INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	NOME_FERTILIZANTE VARCHAR(20) NOT NULL,
	TIPO_FERTILIZANTE VARCHAR(10),
	MARCA_FERT VARCHAR(30),
	PESO_EMBALAGEM VARCHAR (10),
	-- PESO_EMBALAGEM DECIMAL,
	OBSERVACAO VARCHAR(150),
	TIPO_APLIC VARCHAR(20),
	CLASSIF VARCHAR(20)
);

INSERT INTO TB_FERTILIZANTE(NOME_FERTILIZANTE, MARCA_FERT, PESO_EMBALAGEM, OBSERVACAO,TIPO_APLIC,CLASSIF)
VALUES('Fertilizante Liquído','Dimy',2,'Indicado para uso doméstico.','liquido','domestico');

INSERT INTO TB_FERTILIZANTE(NOME_FERTILIZANTE, TIPO_FERTILIZANTE, MARCA_FERT, PESO_EMBALAGEM, OBSERVACAO,TIPO_APLIC,CLASSIF)
VALUES('Fertilizante Forth','Tecnico','Forth',1,'complementar e repor os nutrientes.','spray','domestico');

INSERT INTO TB_FERTILIZANTE(NOME_FERTILIZANTE, TIPO_FERTILIZANTE, MARCA_FERT, PESO_EMBALAGEM, OBSERVACAO,TIPO_APLIC,CLASSIF)
VALUES('Fertilizante TEC','Tecnico','Forth',1,'complementar e repor os nutrientes.','spray','domestico');

INSERT INTO TB_FERTILIZANTE(NOME_FERTILIZANTE, TIPO_FERTILIZANTE, MARCA_FERT, PESO_EMBALAGEM, OBSERVACAO,TIPO_APLIC,CLASSIF)
VALUES('Fertilizante Forth industrial','Tecnico','Forth',1,'complementar e repor os nutrientes.','liquido','industrial');

INSERT INTO TB_FERTILIZANTE(NOME_FERTILIZANTE, TIPO_FERTILIZANTE, MARCA_FERT, PESO_EMBALAGEM, OBSERVACAO,TIPO_APLIC,CLASSIF)
VALUES('Fertilizante Forth 4kg','Tecnico','Forth',4,'complementar e repor os nutrientes.','spray','domestico');



CREATE TABLE TB_PLANTIO (
	ID_PLANTIO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	ID_PLANTA INTEGER NOT NULL,
	ID_FERTILIZANTE INTEGER NOT NULL,
	TIPO_ADUBO VARCHAR(20),
	TEMPO_MED_IRRIGA VARCHAR(10),
	-- TEMPO_MED_IRRIGA DATETIME,
	METRAGEM VARCHAR(20),
	-- METRAGEM DECIMAL,
	QTD_SEMENTE VARCHAR(10),
	-- QTD_SEMENTE INTEGER, 
	TIPO_PLANTIO CHAR(1) NOT NULL  CHECK (TIPO_PLANTIO  IN ('H','F','L')),  -- H - Hortaliças | F - Frutas | L - Legumes
	DT_INI_PLANTIO DATETIME NOT NULL,
	DT_FIM_PLANTIO DATETIME,
	DT_INI_COLHEITA DATETIME,
	DT_FIM_COLHEITA DATETIME,
	FOREIGN KEY(ID_PLANTA) REFERENCES TB_PLANTA (ID_PLANTA),
	FOREIGN KEY(ID_FERTILIZANTE) REFERENCES TB_FERTILIZANTE (ID_FERTILIZANTE)
);
INSERT INTO TB_PLANTIO(ID_PLANTA, ID_FERTILIZANTE, DT_INI_PLANTIO, QTD_SEMENTE, TIPO_PLANTIO)
VALUES(1,1,'02/10/2021','1000','H');

INSERT INTO TB_PLANTIO(ID_PLANTA, ID_FERTILIZANTE, DT_INI_PLANTIO, QTD_SEMENTE, TIPO_PLANTIO)
VALUES(2,1,'01/10/2021','1000','F');

INSERT INTO TB_PLANTIO(ID_PLANTA, ID_FERTILIZANTE, DT_INI_PLANTIO, TIPO_PLANTIO)
VALUES(1,2,'01/01/2021');

INSERT INTO TB_PLANTIO(ID_PLANTA, ID_FERTILIZANTE, DT_INI_PLANTIO, QTD_SEMENTE)
VALUES(3,2,'01/11/2021','200','L');

INSERT INTO TB_PLANTIO(ID_PLANTA, ID_FERTILIZANTE, DT_INI_PLANTIO, QTD_SEMENTE)
VALUES(4,4,'01/03/2021',5000);


-- TABELA DE TAREFAS
CREATE TABLE TB_TAREFAS(
	ID_TAREFA INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	ID_USUARIO INTEGER NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL,
	OBS_TAREFA VARCHAR(150),
	DT_REAL_TAREFA DATETIME, --DATA QUE A TAREFA FOI EXECUTADA
	DT_PREVISTA DATETIME, -- DATA PREVISTA PARA REALIZAÇÃO DA TAREFA
	TIPO_TAREFA CHAR(1) NOT NULL CHECK (TIPO_TAREFA IN ('C','A')), -- C - COLHEITA | A- AVALIAÇÃO  
	STATUS_TAREFA CHAR(1) NOT NULL  CHECK (STATUS_TAREFA IN ('P','F')),  -- P - PENDENTE | F - FINALIZADA
	FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
);
INSERT INTO TB_TAREFAS(DESCRICAO, ID_USUARIO, TIPO_TAREFA, STATUS_TAREFA)
VALUES('colheita alface',1,'C','P');

INSERT INTO TB_TAREFAS(DESCRICAO, ID_USUARIO, TIPO_TAREFA, STATUS_TAREFA)
VALUES('plantio',1,'P','F');

INSERT INTO TB_TAREFAS(DESCRICAO, ID_USUARIO, TIPO_TAREFA, STATUS_TAREFA)
VALUES('avaliação da produção',2,'A','P');

INSERT INTO TB_TAREFAS(DESCRICAO, ID_USUARIO, TIPO_TAREFA, STATUS_TAREFA)
VALUES('plantio',3,'P','F');

INSERT INTO TB_TAREFAS(DESCRICAO, ID_USUARIO, TIPO_TAREFA, STATUS_TAREFA)
VALUES('produção da produção',5,'A','P');

-- VINCULO ENTRE PLANTIO E TAREFAS
CREATE TABLE TB_TAREF_PLANTIO(
	ID_TAREF_PLANTIO INTEGER PRIMARY KEY NOT NULL IDENTITY(1,1),
	ID_TAREFA INTEGER NOT NULL,
	ID_PLANTIO INTEGER NOT NULL,
	FOREIGN KEY(ID_TAREFA) REFERENCES TB_TAREFAS (ID_TAREFA),
	FOREIGN KEY(ID_PLANTIO) REFERENCES TB_PLANTIO (ID_PLANTIO)
);
INSERT INTO TB_TAREF_PLANTIO(ID_TAREFA, ID_PLANTIO)
VALUES(1,2);
INSERT INTO TB_TAREF_PLANTIO(ID_TAREFA, ID_PLANTIO)
VALUES(2,2);
INSERT INTO TB_TAREF_PLANTIO(ID_TAREFA, ID_PLANTIO)
VALUES(2,3);
INSERT INTO TB_TAREF_PLANTIO(ID_TAREFA, ID_PLANTIO)
VALUES(3,2);
INSERT INTO TB_TAREF_PLANTIO(ID_TAREFA, ID_PLANTIO)
VALUES(4,4);